Repository streamnative/charts, pull requests merged in 2020-04, with the labels that each got.

#44 Fix CI error
  .github/workflows/pulsar.yml
  .github/workflows/pulsar_bk_tls.yml
  .github/workflows/pulsar_broker_tls.yml
  .github/workflows/pulsar_function.yml
  .github/workflows/pulsar_image.yml
  .github/workflows/pulsar_jwt_asymmetric.yml
  .github/workflows/pulsar_jwt_symmetric.yml
  .github/workflows/pulsar_tls.yml
  .github/workflows/pulsar_zk_tls.yml
  .github/workflows/pulsar_zkbk_tls.yml
Labels: area/ci

#55 Enable TLS & Authentication for KoP
  charts/pulsar/templates/_autorecovery.tpl
  charts/pulsar/templates/_bookkeeper.tpl
  charts/pulsar/templates/_broker.tpl
  charts/pulsar/templates/_proxy.tpl
  charts/pulsar/templates/_toolset.tpl
  charts/pulsar/templates/_zookeeper.tpl
  charts/pulsar/templates/bookkeeper-cluster-initialize.yaml
  charts/pulsar/templates/broker-cluster-role-binding.yaml
  charts/pulsar/templates/broker-configmap.yaml
  charts/pulsar/templates/broker-service.yaml
  charts/pulsar/templates/broker-statefulset.yaml
  charts/pulsar/templates/keytool.yaml
  charts/pulsar/templates/proxy-statefulset.yaml
  charts/pulsar/templates/pulsar-cluster-initialize.yaml
  charts/pulsar/templates/pulsar-manager-initialize.yaml
  charts/pulsar/templates/tls-certs-internal.yaml
  charts/pulsar/templates/toolset-configmap.yaml
  charts/pulsar/templates/toolset-statefulset.yaml
  charts/pulsar/values.yaml
Labels: workflow::in-review

#53 Enable custom runtime options
  charts/pulsar/templates/_broker.tpl
  charts/pulsar/templates/broker-configmap.yaml
  charts/pulsar/templates/broker-statefulset.yaml
  charts/pulsar/values.yaml
Labels: workflow::in-review

#65 Add proxy datadog annotation
  charts/pulsar/templates/_proxy.tpl
  charts/pulsar/templates/proxy-statefulset.yaml
Labels: area/charts
