Repository streamnative/charts, pull requests merged in 2022-12, with the labels that each got.

#892 [BREAK CHANGE]: remove local_storage config in sn-platform chart
  charts/sn-platform/templates/bookkeeper/_bookkeeper.tpl
  charts/sn-platform/templates/bookkeeper/bookkeeper-storageclass.yaml
  charts/sn-platform/templates/grafana/_grafana.tpl
  charts/sn-platform/templates/grafana/grafana-pvc.yaml
  charts/sn-platform/templates/prometheus/_prometheus.tpl
  charts/sn-platform/templates/prometheus/prometheus-pvc.yaml
  charts/sn-platform/templates/streamnative-console/_streamnative-console.tpl
  charts/sn-platform/templates/streamnative-console/streamnative-console-pvc.yaml
  charts/sn-platform/templates/vault/_vault.tpl
  charts/sn-platform/templates/zookeeper/_zookeeper.tpl
  charts/sn-platform/templates/zookeeper/zookeeper-storageclass.yaml
  charts/sn-platform/values.yaml
Labels: doc-required, break-change, release-sn-platform/1.8.0

#918 Fixed console init failed
  charts/sn-platform/values.yaml
Labels: doc-info-missing

#909 BREAKING CHANGE(sn-platform): update zk reconfig
  charts/sn-platform/templates/zookeeper/zookeeper-backup-statefulset.yaml
  charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
  charts/sn-platform/values.yaml
  examples/sn-platform/zk-dynamic-reconfig.yaml
Labels: no-need-doc, break-change

#898 BREAKING CHANGE(sn-platform): remove auto scale config
  charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/proxy/proxy-cluster.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, break-change, release-sn-platform/1.8.0

#923 Update console version for fixed curl missing issue
  charts/sn-console/values.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, need-cherry-pick/1.6, need-cherry-pick/1.7

#927 fix(ci): remove local_storage in CI and upgrade kind k8s version to 1.20
  .ci/chart_test.sh
  .ci/clusters/values-bk-tls.yaml
  .ci/clusters/values-broker-tls.yaml
  .ci/clusters/values-function.yaml
  .ci/clusters/values-jwt-asymmetric.yaml
  .ci/clusters/values-jwt-symmetric.yaml
  .ci/clusters/values-local-pv.yaml
  .ci/clusters/values-tls.yaml
  .ci/clusters/values-zk-tls.yaml
  .ci/clusters/values-zkbk-tls.yaml
  .ci/helm.sh
  .github/workflows/pulsar_upgrade.yml
  examples/pulsar/values-local-pv.yaml
  hack/kind-cluster-build.sh
Labels: no-need-doc

#921 bump(image): bump sn-platform image version
  charts/sn-platform/Chart.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc

#919 Fix wrong field for cert-manager Issuer
  charts/pulsar/templates/tls/tls-cert-public-issuer.yaml
  charts/sn-platform/templates/tls/istio/tls-cert-public-issuer.yaml
  charts/sn-platform/templates/tls/tls-cert-public-issuer.yaml
Labels: no-need-doc

#924 [sn-platform] Support customize internal Issuer
  charts/sn-platform/templates/tls/istio/tls-cert-internal-issuer.yaml
  charts/sn-platform/templates/tls/istio/tls-certs.yaml
  charts/sn-platform/templates/tls/tls-cert-internal-issuer.yaml
  charts/sn-platform/values.yaml
Labels: doc-required
