Repository streamnative/charts, pull requests merged in 2022-08, with the labels that each got.

#822 feat(sn-platform): add some usage example values
  examples/sn-platform/values-no-vault.yaml
  examples/sn-platform/values-proxy-with-istio.yaml
Labels: no-need-doc

#830 feat(sn-platform): add more sn-platform usage examples
  examples/sn-platform/values-broker-override-config.yaml
  examples/sn-platform/values-proxy-with-ingress.yaml
Labels: no-need-doc

#814 Add support for zone anti_affinity, refactor affinity
  charts/sn-platform/templates/_helpers.tpl
  charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/function-worker/function-worker-statefulset.yaml
  charts/sn-platform/templates/presto/presto-coordinator-statefulset.yaml
  charts/sn-platform/templates/presto/presto-worker-statefulset.yaml
  charts/sn-platform/templates/prometheus/prometheus-statefulset.yaml
  charts/sn-platform/templates/proxy/proxy-cluster.yaml
  charts/sn-platform/templates/zookeeper/zookeeper-backup-statefulset.yaml
  charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
  charts/sn-platform/values.yaml
Labels: doc-info-missing, release-sn-platform/1.6.1, release-sn-platform/1.5.5

#829 [charts/sn-platform]: Make Presto compatible for Istio mode
  charts/sn-platform/templates/presto/_presto.tpl
  charts/sn-platform/templates/presto/presto-authrozationpolicy.yaml
  charts/sn-platform/templates/presto/presto-destinationrule.yaml
  charts/sn-platform/templates/presto/presto-gateway.yaml
  charts/sn-platform/templates/presto/presto-service-ingress.yaml
  charts/sn-platform/templates/presto/presto-serviceentry.yaml
  charts/sn-platform/templates/presto/presto-virtualservice.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.6.1

#823 Adding support for cloudflare in public certificate issuing process
  charts/pulsar/templates/tls/tls-cert-public-issuer.yaml
  charts/pulsar/values.yaml
  charts/sn-platform/templates/tls/istio/tls-cert-public-issuer.yaml
  charts/sn-platform/templates/tls/tls-cert-public-issuer.yaml
  charts/sn-platform/values.yaml
Labels: doc-info-missing, release-sn-platform/1.6.1

#834 [sn-platform] Fix resources limits for broker metadata init job
  charts/sn-platform/templates/broker/broker-cluster.yaml
Labels: no-need-doc, release-sn-platform/1.6.1, release-sn-platform/1.5.5

#835 [sn-platform] Fix broker initJob definition
  charts/sn-platform/templates/broker/broker-cluster.yaml
Labels: no-need-doc

#836 upgrade console image to v1.30.1
  charts/sn-platform/values.yaml
Labels: no-need-doc

#832 feat(operator): Add some extra configs on operator deployment
  charts/pulsar-operator/templates/bookkeeper-operator/operator.yaml
  charts/pulsar-operator/templates/pulsar-operator/operator.yaml
  charts/pulsar-operator/templates/zookeeper-operator/operator.yaml
Labels: no-need-doc, release-pulsar-operators-release/0.12.1

#679 [charts/pulsar] Added an ability to set annotations for statefulsets
  charts/pulsar/templates/bookkeeper/bookkeeper-autorecovery-statefulset.yaml
  charts/pulsar/templates/bookkeeper/bookkeeper-statefulset.yaml
  charts/pulsar/templates/broker/broker-statefulset.yaml
  charts/pulsar/templates/detector/pulsar-detector-statefulset.yaml
  charts/pulsar/templates/function-worker/function-worker-statefulset.yaml
  charts/pulsar/templates/presto/presto-worker-statefulset.yaml
  charts/pulsar/templates/proxy/proxy-statefulset.yaml
  charts/pulsar/templates/pulsar-manager/pulsar-manager-statefulset.yaml
  charts/pulsar/templates/tls/tls-cert-internal-issuer.yaml
  charts/pulsar/templates/tls/tls-certs-internal.yaml
  charts/pulsar/templates/toolset/toolset-statefulset.yaml
  charts/pulsar/templates/zookeeper/zookeeper-statefulset.yaml
  charts/pulsar/values.yaml
Labels: no-need-doc

#844 [sn-platform] Toolset add build-in busybox/vim command
  charts/sn-platform/templates/toolset/toolset-statefulset.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc

#847 feat(sn-platform): add missing labels config for several components
  charts/sn-platform/templates/alert-manager/alertmanager-deployment.yaml
  charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
  charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml
  charts/sn-platform/templates/grafana/grafana-deployment.yaml
  charts/sn-platform/templates/node-exporter/node-exporter.yaml
  charts/sn-platform/templates/presto/presto-coordinator-statefulset.yaml
  charts/sn-platform/templates/presto/presto-worker-statefulset.yaml
  charts/sn-platform/templates/prometheus/prometheus-statefulset.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
  charts/sn-platform/templates/toolset/toolset-statefulset.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.6.2

#851 [Pulsar] Add oauth2 support for pulsar charts
  charts/pulsar/templates/broker/_broker.tpl
  charts/pulsar/templates/broker/broker-configmap.yaml
  charts/pulsar/templates/broker/broker-statefulset.yaml
  charts/pulsar/templates/oauth2/oauth2-secret.yaml
  charts/pulsar/templates/proxy/_proxy.tpl
  charts/pulsar/templates/proxy/proxy-configmap.yaml
  charts/pulsar/templates/proxy/proxy-statefulset.yaml
  examples/pulsar/values-oauth2.yaml
Labels: doc-required
