Repository streamnative/charts, pull requests merged in 2022-07, with the labels that each got.

#782 [pulsar] Support proxy service port mapping in toolset
  charts/pulsar/templates/toolset/_toolset.tpl
Labels: no-need-doc

#786 feat(sn-platform): support vault metrics expose
  charts/sn-platform/templates/prometheus/prometheus-configmap.yaml
  charts/sn-platform/templates/vault/vault-statefulset.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.6.0

#759 feat(sn-platform): Add kop TransactionCoordinatorEnabled config support
  charts/sn-platform/templates/broker/broker-cluster.yaml
Labels: no-need-doc, release-sn-platform/1.6.0

#768 [sn-platform]: Remove deprecated image configs
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.6.0

#783 Add test value files for long-running test env
  license_test.go
  test-values/pulsar-operator/default.yaml
  test-values/sn-platform/1.3/normal.yaml
  test-values/sn-platform/1.4/normal.yaml
  test-values/sn-platform/1.5/normal.yaml
Labels: no-need-doc

#791 Use latest grafana image (based on 8.4.3 Grafana)
  charts/pulsar/values.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc

#788 feat(sn-platform): bump sn-platform images from 2.9.2.17 to 2.9.2.20
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.6.0

#790 [sn-platform] Improve function-worker compatibility
  charts/sn-platform/templates/broker/function-worker-configfile-configmap.yaml
  charts/sn-platform/templates/function-worker/_function_worker.tpl
  charts/sn-platform/templates/function-worker/function-worker-authorizationpolicy.yaml
  charts/sn-platform/templates/function-worker/function-worker-statefulset.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.6.0, release-sn-platform/1.5.4

#795 Trigger the pulsar workflow only when pulsar-related workflows are updated
  .github/workflows/long_running_tests.yml
  .github/workflows/pulsar.yml
  .github/workflows/pulsar_bk_tls.yml
  .github/workflows/pulsar_broker_ip.yml
  .github/workflows/pulsar_broker_tls.yml
  .github/workflows/pulsar_function.yml
  .github/workflows/pulsar_image.yml
  .github/workflows/pulsar_jwt_asymmetric.yml
  .github/workflows/pulsar_jwt_symmetric.yml
  .github/workflows/pulsar_sa_disabled.yml
  .github/workflows/pulsar_service_account.yml
  .github/workflows/pulsar_tls.yml
  .github/workflows/pulsar_upgrade.yml
  .github/workflows/pulsar_zk_tls.yml
  .github/workflows/pulsar_zkbk_tls.yml
Labels: no-need-doc

#798 [sn-platform] Add missing imagePullSecrets
  charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
  charts/sn-platform/templates/vault/vault-clear-resource.yaml
Labels: no-need-doc

#800 Support AoP in Istio.
  charts/pulsar-operator/Chart.yaml
  charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
  charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml
  charts/pulsar-operator/values.yaml
  charts/sn-platform/templates/broker/broker-authorizationpolicy.yaml
Labels: doc-required

#801 Fix function-worker template
  charts/sn-platform/templates/function-worker/function-worker-statefulset.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.6.0

#804 Update operator to v0.12.0
  charts/pulsar-operator/Chart.yaml
  charts/pulsar-operator/values.yaml
Labels: doc-info-missing

#806 Update console version to 1.13.0 for fixed security issue
  charts/sn-console/Chart.yaml
  charts/sn-console/values.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.6.0

#805 Add Dockerfile, update image version, fixed security issue
  charts/sn-platform-vault/scripts/Dockerfile
  charts/sn-platform-vault/values.yaml
  charts/sn-platform/values.yaml
Labels: doc-info-missing, planned-sn-platform-release/1.6, release-sn-platform/1.6.0

#792 feat(sn-platform): Ignore istio,console for prometheus when istio enabled
  charts/sn-platform/templates/prometheus/prometheus-configmap.yaml
Labels: no-need-doc, release-sn-platform/1.6.0

#807 [Pulsar]Update to use cert-manager v1 version.
  charts/pulsar/templates/tls/tls-cert-internal-issuer.yaml
  charts/pulsar/templates/tls/tls-cert-public-issuer.yaml
  charts/pulsar/templates/tls/tls-certs-internal.yaml
  charts/pulsar/templates/tls/tls-certs-public.yaml
  charts/pulsar/values.yaml
Labels: no-need-doc

#808 Remove unused capability and set `allowedCapabilities` only when vault is enabled
  charts/sn-platform/templates/openshift/scc.yaml
Labels: no-need-doc

#813 Update gke cluster info
  .github/workflows/long_running_tests.yml
Labels: no-need-doc

#811 Update ZooKeeper dynamic reconfig.
  charts/pulsar/templates/zookeeper/zookeeper-configmap.yaml
Labels: doc-info-missing

#816 Fix tls related issue in pulsar charts:
  charts/pulsar/templates/broker/function-worker-configfile-configmap.yaml
  charts/pulsar/templates/tls/tls-certs-internal.yaml
Labels: no-need-doc

#818 [sn-platform] Support resources limits for init containers
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml
  charts/sn-platform/templates/function-worker/function-worker-statefulset.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
  charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc
