Repository streamnative/charts, pull requests merged in 2022-11, with the labels that each got.

#887 [sn-platform]: bump pulsar image to 2.10 base
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.7.0

#889 BREAKING CHANGE(sn-platform): remove pdb config in detector
  charts/sn-platform/templates/detector/pulsar-detector-pdb.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.7.0, break-change

#888 [charts] Add the Google BigQuery connector
  charts/sn-platform/conf/broker/connectors.yaml
Labels: no-need-doc, release-sn-platform/1.7.0

#890 fix(toolset): set toolset run as root by default
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.7.0

#899 Fix trailing spaces reported by chart linter
  charts/sn-platform/values.yaml
Labels: no-need-doc

#896 feat(connector): add debezium oracle source
  charts/sn-platform/conf/broker/connectors.yaml
Labels: no-need-doc

#897 Support jwt authentication on sn-platform
  charts/sn-platform/templates/_helpers.tpl
  charts/sn-platform/templates/broker/_broker.tpl
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml
  charts/sn-platform/templates/function-worker/_function_worker.tpl
  charts/sn-platform/templates/function-worker/function-worker-statefulset.yaml
  charts/sn-platform/templates/proxy/_proxy.tpl
  charts/sn-platform/templates/proxy/proxy-cluster.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
  charts/sn-platform/templates/vault/vault-clear-resource.yaml
  charts/sn-platform/templates/vault/vault-initialize.yaml
  charts/sn-platform/values.yaml
Labels: doc-required

#901 [sn-platform] Fix Presto JMX exporter enable condition
  charts/sn-platform/templates/presto/presto-coordinator-configmap.yaml
  charts/sn-platform/templates/presto/presto-coordinator-deployment.yaml
  charts/sn-platform/templates/presto/presto-worker-configmap.yaml
  charts/sn-platform/templates/presto/presto-worker-deployment.yaml
Labels: no-need-doc, release-sn-platform/1.7.1

#893 [BREAK CHANGE]: remove resource cr in sn-platform
  charts/sn-platform/templates/entities/_entities.tpl
  charts/sn-platform/templates/entities/connection.yaml
  charts/sn-platform/templates/entities/namespaces.yaml
  charts/sn-platform/templates/entities/permissions.yaml
  charts/sn-platform/templates/entities/tenants.yaml
  charts/sn-platform/templates/entities/topics.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, break-change, release-sn-platform/1.8.0

#895 Update datadog token auth
  charts/sn-platform/templates/proxy/_proxy.tpl
  charts/sn-platform/templates/proxy/_websocket.tpl
Labels: no-need-doc

#911 [sn-platform] Fix unable to start broker and proxy when auth and vault disabled
  charts/sn-platform/templates/_helpers.tpl
  charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml
Labels: no-need-doc

#903 Remove resources related crd in pulsar-operator
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarconnections.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarnamespaces.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarpermissions.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsartenants.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsartopics.yaml
Labels: no-need-doc

#907 feat(sn-platform): enable topic level policies by default
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.8.0

#913 Fixed add authentication check for oauth2
  charts/sn-platform/templates/_helpers.tpl
  charts/sn-platform/values.yaml
Labels: type/bug, no-need-doc

#906 BREAKING CHANGE(sn-platform): deprecate `.Values.datadog.namespace` config
  charts/sn-platform/templates/bookkeeper/_bookkeeper.tpl
  charts/sn-platform/templates/broker/_broker.tpl
  charts/sn-platform/templates/prometheus/_prometheus.tpl
  charts/sn-platform/templates/proxy/_proxy.tpl
  charts/sn-platform/templates/zookeeper/_zookeeper.tpl
  charts/sn-platform/values.yaml
Labels: doc-added, break-change, release-sn-platform/1.8.0

#914 Add insecureAuthEnabled field
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
Labels: no-need-doc

#915 Update CODEOWNERS: Remove platform team
  .github/CODEOWNERS
Labels: doc-info-missing
