Repository streamnative/charts, pull requests merged in 2022-03, with the labels that each got.

#497 [workflow] Fix pull request template doc
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no-need-doc

#499 Fix datadog annotation for bk/zk/broker/proxy
  .ci/clusters/values-datadog.yaml
  .github/workflows/sn-platform.yml
  charts/sn-platform/templates/bookkeeper/_bookkeeper.tpl
  charts/sn-platform/templates/broker/_broker.tpl
  charts/sn-platform/templates/proxy/_proxy.tpl
  charts/sn-platform/templates/zookeeper/_zookeeper.tpl
Labels: no-need-doc, release/v1.2.34

#501 Update sn platform version to 1.2.34
  charts/sn-platform/Chart.yaml
Labels: no-need-doc

#505 Update telemetry default value
  charts/sn-platform/values.yaml
Labels: doc-info-missing, release/v1.2.35

#500 Allow customize Pulsar Cluster name for operator deployment.
  charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
  charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml
  charts/pulsar-operator/templates/pulsar-operator/rbac.yaml
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/proxy/proxy-cluster.yaml
Labels: no-need-doc

#509 [charts/pulsar] Fix issues with openshift deployments
  charts/pulsar/templates/control-center/_control_center.tpl
  charts/pulsar/templates/control-center/control-center-ingress.yaml
  charts/pulsar/values.yaml
Labels: no-need-doc

#487 Support no vault for auth
  charts/sn-console/templates/console/streamnative-console-initialize.yaml
  charts/sn-console/templates/console/streamnative-console-statefulset.yaml
  charts/sn-console/values.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
  charts/sn-platform/values.yaml
Labels: doc-required, release/v1.2.35

#515 Upgrade sn platform and sn console version
  charts/sn-console/Chart.yaml
  charts/sn-platform/Chart.yaml
Labels: doc-info-missing

#518 Update sn platform version to 1.2.36
  charts/sn-platform/Chart.yaml
Labels: doc-info-missing

#514 Add `trustCertsEnabled` to set `kop.tls` configuration item `kopSslTruststoreLocation`
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release/v1.2.37

#520 Update local-storage-provisioner chart version to 1.1.0
  charts/local-storage-provisioner/Chart.yaml
Labels: no-need-doc

#512 Add presto tls related resources.
  charts/pulsar/templates/broker/function-worker-configfile-configmap.yaml
  charts/pulsar/templates/presto/presto-coordinator-configmap.yaml
  charts/pulsar/templates/presto/presto-coordinator-statefulset.yaml
  charts/pulsar/templates/presto/presto-worker-configmap.yaml
  charts/pulsar/templates/presto/presto-worker-statefulset.yaml
  charts/pulsar/templates/tls/tls-certs-internal.yaml
  charts/pulsar/templates/zookeeper/_zookeeper.tpl
Labels: no-need-doc

#526 Expose console backend port
  charts/sn-platform/conf/streamnative_console/init_instance.py
  charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-service.yaml
Labels: no-need-doc

#511 Merge support for adoption of some ZK and BK resources
  charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
  charts/sn-platform/templates/bookkeeper/bookkeeper-statefulset.yaml
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/broker/broker-statefulset.yaml
  charts/sn-platform/templates/detector/pulsar-detector-statefulset.yaml
  charts/sn-platform/templates/extra.yaml
  charts/sn-platform/templates/presto/presto-coordinator-configmap.yaml
  charts/sn-platform/templates/presto/presto-worker-configmap.yaml
  charts/sn-platform/templates/prometheus/prometheus-statefulset.yaml
  charts/sn-platform/templates/proxy/proxy-cluster.yaml
  charts/sn-platform/templates/proxy/proxy-statefulset.yaml
  charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
  charts/sn-platform/templates/zookeeper/zookeeper-statefulset.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc

#524 Toolset extra env
  charts/pulsar/templates/toolset/toolset-statefulset.yaml
  charts/pulsar/values.yaml
  charts/sn-platform/templates/toolset/toolset-statefulset.yaml
  charts/sn-platform/values.yaml
Labels: doc-info-missing

#535 Support ImagePullSecrets in pulsar components
  charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
  charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml
  charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/proxy/proxy-cluster.yaml
  charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
  charts/sn-platform/values.yaml
Labels: doc-required, release/v1.2.37

#532 Update value example file for support offload configuration
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/values.yaml
Labels: doc-required, no-need-doc, release/v1.2.37

#540 Add doc for configuring LB tls termination.
  charts/sn-platform/README.md
Labels: no-need-doc

#541 release: bump sn-platform chart version to 1.2.37
  charts/sn-platform/Chart.yaml
Labels: no-need-doc, release/v1.2.37

#542 [pulsar-operator] upgrade operators
  charts/pulsar-operator/Chart.yaml
  charts/pulsar-operator/values.yaml
Labels: no-need-doc

#543 release: bump sn-platform chart version to 1.2.38
  charts/sn-platform/Chart.yaml
Labels: no-need-doc

#544 Feature support configuration azure blob offload
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
  charts/sn-platform/values.yaml
Labels: doc-required, need-cherry-pick/1.3

#528 [charts/sn-platform] Support exposing broker and kop on istio
  charts/sn-platform/templates/_helpers.tpl
  charts/sn-platform/templates/bookkeeper/bookkeeper-authorizationpolicy.yaml
  charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
  charts/sn-platform/templates/broker/_broker.tpl
  charts/sn-platform/templates/broker/broker-authorizationpolicy.yaml
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/control-center/control-center-gateway.yaml
  charts/sn-platform/templates/control-center/control-center-virtualservice.yaml
  charts/sn-platform/templates/detector/pulsar-detector-statefulset.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-authorizationpolicy.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
  charts/sn-platform/templates/vault/vault-authorizationpolicy.yaml
  charts/sn-platform/templates/vault/vault-clear-resource.yaml
  charts/sn-platform/templates/vault/vault-initialize-public-key.yaml
  charts/sn-platform/templates/vault/vault-initialize.yaml
  charts/sn-platform/templates/vault/vault-statefulset.yaml
  charts/sn-platform/templates/zookeeper/_zookeeper.tpl
  charts/sn-platform/templates/zookeeper/zookeeper-authorizationpolicy.yaml
  charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
  charts/sn-platform/templates/zookeeper/zookeeper-service-account.yaml
  charts/sn-platform/values.yaml
Labels: doc-required, release/1.3.0

#549 fix(charts): remove needless images on sn-platform values
  charts/sn-platform/values.yaml
Labels: no-need-doc, release/1.3.0

#551 Adjust the syntax position of imagePullSecrets in helm templates
  charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
  charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
Labels: no-need-doc

#546 Support additional annotation on vault and pulsar_detector.
  charts/sn-platform/templates/detector/pulsar-detector-statefulset.yaml
  charts/sn-platform/templates/vault/vault-statefulset.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release/1.3.0

#557 [charts/sn-platform] Fix certificate templates
  charts/sn-platform/templates/tls/tls-certs-internal.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release/1.3.0, need-cherry-pick/1.2

#561 Support the configmap name of builtin connectors with release name as a prefix
  charts/sn-platform/templates/broker/_broker.tpl
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/broker/broker-configmap-functionmesh.yaml
Labels: no-need-doc, release/1.3.0

#552 Add doc for installing multiple pulsar cluster in one k8s
  charts/sn-platform/README.md
Labels: no-need-doc, release/1.3.0

#553 Fixed remove offload use flag
  .ci/chart_test.sh
  charts/pulsar/templates/broker/broker-configmap.yaml
  charts/pulsar/values.yaml
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/broker/broker-configmap.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release/1.3.0

#560 Allow customizing port exposed by Proxy ingress service.
  charts/sn-platform/templates/proxy/proxy-cluster.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release/1.3.0

#547 Add option to turn off prometheus scarping annotation.
  charts/sn-platform/templates/bookkeeper/bookkeeper-autorecovery-statefulset.yaml
  charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
  charts/sn-platform/templates/bookkeeper/bookkeeper-statefulset.yaml
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/broker/broker-statefulset.yaml
  charts/sn-platform/templates/control-center/ingress-controller-deployment.yaml
  charts/sn-platform/templates/function-worker/function-worker-statefulset.yaml
  charts/sn-platform/templates/node-exporter/node-exporter.yaml
  charts/sn-platform/templates/proxy/proxy-cluster.yaml
  charts/sn-platform/templates/proxy/proxy-statefulset.yaml
  charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
  charts/sn-platform/templates/zookeeper/zookeeper-statefulset.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release/1.3.0

#565 Add port name in ExternalServiceTemplate for http port override.
  charts/sn-platform/templates/proxy/proxy-cluster.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc

#564 release: bump sn-platform chart to 1.3.0
  charts/sn-platform/Chart.yaml
Labels: no-need-doc, release/1.3.0

#568 release: bump chart pulsar 2.8.5
  charts/pulsar/Chart.yaml
Labels: no-need-doc

#548 [CI] Support SN branch versioning to release
  .ci/release.sh
  .github/workflows/release.yml
Labels: no-need-doc

#506 Remove unnecessary jvm parameters
  charts/sn-platform/values.yaml
Labels: doc-required, no-need-doc

#572 Fix the manifest issue that makes some fields out of the `components.vault` control
  charts/sn-platform/templates/vault/vault-statefulset.yaml
Labels: no-need-doc, need-cherry-pick/1.3, release/1.4.0, release/1.3.1
