Repository streamnative/charts, pull requests merged in 2022-09, with the labels that each got.

#855 [charts/pulsar] fix proxy authentication error:
  charts/pulsar/templates/proxy/proxy-configmap.yaml
Labels: no-need-doc

#856 Fix bug with custom rules and new affinity logic
  charts/sn-platform/templates/_helpers.tpl
Labels: doc-info-missing, release-sn-platform/1.6.2

#859 [pulsar-operator] Upgrade to v0.12.3
  charts/pulsar-operator/Chart.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
  charts/pulsar-operator/values.yaml
Labels: no-need-doc

#853 [sn-platform] Make proxy compatible for Istio mode
  charts/sn-platform/templates/function-worker/_function_worker.tpl
  charts/sn-platform/templates/function-worker/function-worker-statefulset.yaml
  charts/sn-platform/templates/proxy/proxy-authorizationpolicy.yaml
  charts/sn-platform/templates/proxy/proxy-cluster.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.6.2

#862 bump(sn-platform): bump sn-platform image version
  charts/sn-platform/values.yaml
Labels: no-need-doc
