Repository streamnative/charts, pull requests merged in 2023-07, with the labels that each got.

#1054 [sn-platform-slim] Sync console securityContext changes
  charts/sn-platform-slim/templates/streamnative-console/streamnative-console-initialize.yaml
  charts/sn-platform-slim/values.yaml
Labels: no-need-doc

#1056 [sn-platform][sn-platform-slim] Fix pulsarctl config
  charts/sn-platform-slim/templates/toolset/_toolset.tpl
  charts/sn-platform-slim/templates/toolset/toolset-statefulset.yaml
  charts/sn-platform/templates/toolset/_toolset.tpl
  charts/sn-platform/templates/toolset/toolset-statefulset.yaml
Labels: no-need-doc

#1053 Update proxy.yaml example
  examples/pulsar-operators/proxy.yaml
Labels: doc-info-missing

#1060 [sn-platform][sn-platform-slim]: add resources param to the console gateway
  charts/sn-platform-slim/templates/streamnative-console/streamnative-console-statefulset.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
Labels: no-need-doc

#1058 [example] Deploy sn-platform using ArgoCD
  examples/app-of-apps.yaml
  examples/argocd/charts/sn-pulsar/Chart.yaml
  examples/argocd/charts/sn-pulsar/templates/pulsar-operator.yaml
  examples/argocd/charts/sn-pulsar/templates/sn-platform.yaml
  examples/argocd/charts/sn-pulsar/values.yaml
  examples/argocd/values/pulsar-operator.yaml
  examples/argocd/values/sn-platform.yaml
Labels: doc-required

#1059 Update pulsar broker, proxy, zk and bk crd
  charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
  charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml
Labels: no-need-doc

#1061 bump operator to 0.17
  charts/pulsar-operator/Chart.yaml
  charts/pulsar-operator/values.yaml
Labels: no-need-doc

#1064 hotfix: toolset pulsar container wrong command
  .github/workflows/pulsar.yaml
  charts/pulsar-operator/Chart.yaml
  charts/sn-platform-slim/templates/toolset/toolset-statefulset.yaml
  charts/sn-platform/templates/toolset/toolset-statefulset.yaml
Labels: no-need-doc

#1065 improve: change toolset pod as nonroot user
  .github/workflows/pulsar.yml
  charts/sn-platform-slim/templates/toolset/_toolset.tpl
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/templates/toolset/_toolset.tpl
  charts/sn-platform/values.yaml
Labels: no-need-doc

#1063 fix: operator rbac when watching specific namespace
  charts/pulsar-operator/templates/bookkeeper-operator/operator_rbac.yaml
  charts/pulsar-operator/templates/pulsar-operator/operator_rbac.yaml
  charts/pulsar-operator/templates/zookeeper-operator/operator_rbac.yaml
Labels: no-need-doc

#1073 Update ct.yaml to remove function-mesh charts
  ct.yaml
Labels: doc-info-missing

#1074 [sn-platform][sn-platform-slim]: upgrade grafana to support private cloud billing dashboard
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/values.yaml
  examples/argocd-deploy.yaml
  examples/kube-state-metrics.yaml
  examples/sn-platform/values-kube-state-metrics.yaml
Labels: no-need-doc

#1075 fix the example
  examples/sn-platform/values-kube-state-metrics.yaml
Labels: no-need-doc

#1067 [sn-platform][sn-platform-slim]feat: add logConfig support on sn-platform & sn-platform slim charts
  charts/sn-console/Chart.yaml
  charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml
  charts/sn-platform-slim/templates/broker/broker-cluster.yaml
  charts/sn-platform-slim/templates/proxy/proxy-cluster.yaml
  charts/sn-platform-slim/templates/zookeeper/zookeeper-cluster.yaml
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/proxy/proxy-cluster.yaml
  charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
  charts/sn-platform/values.yaml
  examples/pulsar-operators/logConfig.yaml
  examples/sn-platform/logConfig.yaml
Labels: doc-required

#1069 feat: add podLabel support for pulsar components
  charts/pulsar/Chart.yaml
  charts/pulsar/templates/bookkeeper/bookkeeper-autorecovery-statefulset.yaml
  charts/pulsar/templates/bookkeeper/bookkeeper-statefulset.yaml
  charts/pulsar/templates/broker/broker-statefulset.yaml
  charts/pulsar/templates/proxy/proxy-statefulset.yaml
  charts/pulsar/templates/zookeeper/zookeeper-statefulset.yaml
  charts/pulsar/values.yaml
Labels: no-need-doc

#1077 [fix] split multi-namespace in rbac role template
  charts/pulsar-operator/templates/bookkeeper-operator/rbac.yaml
  charts/pulsar-operator/templates/pulsar-operator/pulsar_broker_clusterrole.yaml
  charts/pulsar-operator/templates/pulsar-operator/rbac.yaml
  charts/pulsar-operator/templates/zookeeper-operator/rbac.yaml
Labels: no-need-doc

#1072 Support init jwt secret when create pulsar cluster
  charts/sn-platform-slim/conf/toolset/pulsar/clean_tls.sh
  charts/sn-platform-slim/conf/toolset/pulsar/cleanup_helm_release.sh
  charts/sn-platform-slim/conf/toolset/pulsar/common.sh
  charts/sn-platform-slim/conf/toolset/pulsar/common_auth.sh
  charts/sn-platform-slim/conf/toolset/pulsar/decommission_bookies.sh
  charts/sn-platform-slim/conf/toolset/pulsar/generate_token.sh
  charts/sn-platform-slim/conf/toolset/pulsar/generate_token_secret_key.sh
  charts/sn-platform-slim/conf/toolset/pulsar/get_token.sh
  charts/sn-platform-slim/conf/toolset/pulsar/gke_bootstrap_script.sh
  charts/sn-platform-slim/conf/toolset/pulsar/prepare_helm_release.sh
  charts/sn-platform-slim/conf/toolset/pulsar/setup-clouddns-resolver-service-account.sh
  charts/sn-platform-slim/conf/toolset/pulsar/upload-lets-encrypt-ca.sh
  charts/sn-platform-slim/conf/toolset/pulsar/upload_tls.sh
  charts/sn-platform-slim/templates/toolset/jwt-secret-init-config.yaml
  charts/sn-platform-slim/templates/toolset/jwt-secret-init-job-service-account.yaml
  charts/sn-platform-slim/templates/toolset/jwt-secret-init-job.yaml
  charts/sn-platform/conf/toolset/pulsar/clean_tls.sh
  charts/sn-platform/conf/toolset/pulsar/cleanup_helm_release.sh
  charts/sn-platform/conf/toolset/pulsar/common.sh
  charts/sn-platform/conf/toolset/pulsar/common_auth.sh
  charts/sn-platform/conf/toolset/pulsar/decommission_bookies.sh
  charts/sn-platform/conf/toolset/pulsar/generate_token.sh
  charts/sn-platform/conf/toolset/pulsar/generate_token_secret_key.sh
  charts/sn-platform/conf/toolset/pulsar/get_token.sh
  charts/sn-platform/conf/toolset/pulsar/gke_bootstrap_script.sh
  charts/sn-platform/conf/toolset/pulsar/prepare_helm_release.sh
  charts/sn-platform/conf/toolset/pulsar/setup-clouddns-resolver-service-account.sh
  charts/sn-platform/conf/toolset/pulsar/upload-lets-encrypt-ca.sh
  charts/sn-platform/conf/toolset/pulsar/upload_tls.sh
  charts/sn-platform/templates/toolset/jwt-secret-init-config.yaml
  charts/sn-platform/templates/toolset/jwt-secret-init-job-service-account.yaml
  charts/sn-platform/templates/toolset/jwt-secret-init-job.yaml
Labels: doc-required, release-sn-platform/1.10.6

#1078 bump pulsar version to 2.10.4.7
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.10.6
