Repository streamnative/charts, pull requests merged in 2023-06, with the labels that each got.

#1033 Support extra custom config for prometheus
  charts/sn-platform-slim/templates/prometheus/prometheus-configmap.yaml
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/templates/prometheus/prometheus-configmap.yaml
  charts/sn-platform/values.yaml
Labels: doc-required

#1034 chore: upgrade busybox image to fix CVEs
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc

#1035 [sn-platform][sn-platform-slim]: add the extraEnv support for bk and zk
  charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml
  charts/sn-platform-slim/templates/zookeeper/zookeeper-cluster.yaml
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
  charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc

#1029 add values examples for 3.0 support
  examples/sn-platform/values-pulsar-3.0.yaml
Labels: doc-info-missing

#1037 [sn-platform][sn-platform-slim]: bump platform and console images
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc

#1036 [sn-platform][sn-platform-slim]: add annotation support on toolset and console sts
  charts/sn-platform-slim/templates/streamnative-console/streamnative-console-statefulset.yaml
  charts/sn-platform-slim/templates/toolset/toolset-statefulset.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
  charts/sn-platform/templates/toolset/toolset-statefulset.yaml
Labels: no-need-doc

#1038 [sn-platform][sn-platform-slim] Add if statement for customWorkerConfig
  charts/sn-platform-slim/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/broker/broker-cluster.yaml
Labels: no-need-doc

#1040 Release pulsar operator to v0.16.4
  charts/pulsar-operator/Chart.yaml
  charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
  charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml
  charts/pulsar-operator/values.yaml
Labels: no-need-doc

#1042 Support rootless busybox in toolset
  charts/sn-platform/templates/toolset/toolset-statefulset.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc

#1041 Define securityContext for components
  charts/sn-platform/templates/alert-manager/alertmanager-deployment.yaml
  charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc

#1043 [sn-platform-slim] Sync securityContext changes
  charts/sn-platform-slim/templates/alert-manager/alertmanager-deployment.yaml
  charts/sn-platform-slim/templates/detector/pulsar-detector-deployment.yaml
  charts/sn-platform-slim/templates/streamnative-console/streamnative-console-statefulset.yaml
  charts/sn-platform-slim/templates/toolset/toolset-statefulset.yaml
  charts/sn-platform-slim/values.yaml
Labels: no-need-doc

#1046 Add security context for private cloud console
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
  charts/sn-platform/values.yaml
Labels: doc-info-missing

#1048 [sn-platform][sn-platform-slim]: update to use the operator auto generated jvm memory options.
  charts/sn-platform-slim/templates/_helpers.tpl
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/templates/_helpers.tpl
  charts/sn-platform/values.yaml
Labels: no-need-doc
