Repository streamnative/charts, pull requests merged in 2023-04, with the labels that each got.

#988 [pulsar] fix: use NettyServerCnxnFactory for zookeeper if tls is enabled
  .ci/clusters/values-function.yaml
  .ci/helm.sh
  charts/pulsar/templates/zookeeper/zookeeper-configmap.yaml
Labels: no-need-doc

#990 Only add extra init container when it exists
  charts/pulsar/templates/zookeeper/zookeeper-backup-statefulset.yaml
Labels: no-need-doc

#992 Remove presto ServiceEntry
  charts/sn-platform/templates/presto/presto-serviceentry.yaml
Labels: no-need-doc

#993 Fix the backup pod never get ready because of zk status
  charts/pulsar/templates/zookeeper/zookeeper-backup-statefulset.yaml
Labels: no-need-doc

#996 fix: update the olm default channel to alpha
  examples/pulsar-operators/olm-subscription.yaml
Labels: no-need-doc

#995 [sn-platform]: add vault affinity config support
  charts/sn-platform/templates/vault/vault-statefulset.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc

#1004 [security chart]: remove cp-kafka in toolset pod for security chart
  charts/sn-platform-security/templates/toolset/_toolset.tpl
  charts/sn-platform-security/templates/toolset/toolset-configmap.yaml
  charts/sn-platform-security/templates/toolset/toolset-statefulset.yaml
  charts/sn-platform-security/values.yaml
Labels: no-need-doc, sn-platform-security

#1001 [snp-security]: remove loki in security chart
  charts/sn-platform-security/ci/disable-monitoring-values.yaml
  charts/sn-platform-security/requirements.yaml
  charts/sn-platform-security/templates/grafana/grafana-deployment.yaml
  charts/sn-platform-security/templates/grafana/grafana-statefulset.yaml
  charts/sn-platform-security/templates/grafana/loki-authorizationpolicy.yaml
  charts/sn-platform-security/values.yaml
Labels: no-need-doc, sn-platform-security

#1006 [snp-security]Remove vault component
  charts/sn-platform-security/templates/_helpers.tpl
  charts/sn-platform-security/templates/broker/broker-cluster.yaml
  charts/sn-platform-security/templates/broker/broker-configmap-functionmesh.yaml
  charts/sn-platform-security/templates/proxy/proxy-cluster.yaml
  charts/sn-platform-security/templates/streamnative-console/_streamnative-console.tpl
  charts/sn-platform-security/templates/streamnative-console/streamnative-console-configmap.yaml
  charts/sn-platform-security/templates/streamnative-console/streamnative-console-initialize.yaml
  charts/sn-platform-security/templates/streamnative-console/streamnative-console-statefulset.yaml
  charts/sn-platform-security/templates/toolset/toolset-statefulset.yaml
  charts/sn-platform-security/templates/vault/_vault.tpl
  charts/sn-platform-security/templates/vault/vault-authorizationpolicy.yaml
  charts/sn-platform-security/templates/vault/vault-clear-resource.yaml
  charts/sn-platform-security/templates/vault/vault-configmap.yaml
  charts/sn-platform-security/templates/vault/vault-initialize-public-key.yaml
  charts/sn-platform-security/templates/vault/vault-initialize.yaml
  charts/sn-platform-security/templates/vault/vault-public-key-secret.yaml
  charts/sn-platform-security/templates/vault/vault-service-account.yaml
  charts/sn-platform-security/templates/vault/vault-statefulset.yaml
  charts/sn-platform-security/values.yaml
Labels: no-need-doc, sn-platform-security

#1008 [pulsar-operator] Upgrade to v0.16.0
  charts/pulsar-operator/Chart.yaml
  charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
  charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml
Labels: no-need-doc

#1009 [snp-security]cleanup vault
  charts/sn-platform-security/ci/disable-auth-values.yaml
  charts/sn-platform-security/conf/vault/Dockerfile
  charts/sn-platform-security/conf/vault/create_pulsar_tokens/create_pulsar_tokens.sh
  charts/sn-platform-security/conf/vault/create_pulsar_tokens/ro-superuser.hcl
  charts/sn-platform-security/conf/vault/create_pulsar_tokens/superuser.hcl
  charts/sn-platform-security/conf/vault/init_vault_streamnative_console/ldap-user.hcl
  charts/sn-platform-security/conf/vault/init_vault_streamnative_console/service-account-template.json
  charts/sn-platform-security/conf/vault/init_vault_streamnative_console/service-account.hcl
  charts/sn-platform-security/conf/vault/init_vault_streamnative_console/startup.sh
  charts/sn-platform-security/conf/vault/init_vault_streamnative_console/super-service-account-template.json
  charts/sn-platform-security/conf/vault/init_vault_streamnative_console/super-service-account.hcl
  charts/sn-platform-security/conf/vault/init_vault_streamnative_console/super-user-template.json
  charts/sn-platform-security/conf/vault/init_vault_streamnative_console/super-user.hcl
  charts/sn-platform-security/conf/vault/init_vault_streamnative_console/user-template.json
  charts/sn-platform-security/conf/vault/init_vault_streamnative_console/user.hcl
  charts/sn-platform-security/conf/vault/init_vault_streamnative_console/vault-jwt-init.sh
  charts/sn-platform-security/conf/vault/init_vault_streamnative_console/vault-ldap-init.sh
  charts/sn-platform-security/values.yaml
Labels: no-need-doc, sn-platform-security

#1011 [snp-slim]: remove presto in the slim chart.
  charts/sn-platform-security/templates/presto/_presto.tpl
  charts/sn-platform-security/templates/presto/presto-authrozationpolicy.yaml
  charts/sn-platform-security/templates/presto/presto-coordinator-configmap.yaml
  charts/sn-platform-security/templates/presto/presto-coordinator-deployment.yaml
  charts/sn-platform-security/templates/presto/presto-destinationrule.yaml
  charts/sn-platform-security/templates/presto/presto-gateway.yaml
  charts/sn-platform-security/templates/presto/presto-jmx-exporter-configmap.yaml
  charts/sn-platform-security/templates/presto/presto-service-ingress.yaml
  charts/sn-platform-security/templates/presto/presto-service.yaml
  charts/sn-platform-security/templates/presto/presto-virtualservice.yaml
  charts/sn-platform-security/templates/presto/presto-worker-configmap.yaml
  charts/sn-platform-security/templates/presto/presto-worker-deployment.yaml
  charts/sn-platform-security/templates/presto/presto-worker-service.yaml
  charts/sn-platform-security/values.yaml
Labels: no-need-doc, sn-platform-security

#1010 [snp-slim]: remove metrics server in security chart
  charts/sn-platform-security/templates/custom-metric-server/_custom_metric_server.tpl
  charts/sn-platform-security/templates/custom-metric-server/custom-metric-server-init.yaml
  charts/sn-platform-security/templates/custom-metric-server/custom-metric-server-prometheus.yaml
  charts/sn-platform-security/templates/custom-metric-server/custom-metric-server.yaml
  charts/sn-platform-security/values.yaml
Labels: no-need-doc, sn-platform-security

#1007 Upgrade console version for snp security
  charts/sn-platform-security/templates/detector/pulsar-detector-deployment.yaml
  charts/sn-platform-security/templates/function-worker/_function_worker.tpl
  charts/sn-platform-security/templates/proxy/_proxy.tpl
  charts/sn-platform-security/templates/proxy/_websocket.tpl
  charts/sn-platform-security/templates/streamnative-console/streamnative-console-initialize.yaml
  charts/sn-platform-security/templates/streamnative-console/streamnative-console-statefulset.yaml
  charts/sn-platform-security/values.yaml
Labels: doc-info-missing

#999 Support private cloud console
  charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc

#1005 [sn-platform][feat]: add authenticateMetricsEndpoint on Proxy
  charts/sn-platform/templates/proxy/_proxy.tpl
  charts/sn-platform/templates/proxy/proxy-cluster.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc

#1013 [sn-platform][sn-platform-slim]: bump grafana image version
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc
