Repository streamnative/charts, pull requests merged in 2023-01, with the labels that each got.

#929 [pulsar-operator] Upgrade to v0.14.0
  charts/pulsar-operator/Chart.yaml
  charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
  charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml
  charts/pulsar-operator/values.yaml
Labels: no-need-doc

#932 [sn-platform] Make annotation merge-metrics configurable
  charts/sn-platform/templates/_helpers.tpl
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.7.2

#931 Support to add custom annotations and labels for CR
  charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/proxy/proxy-cluster.yaml
  charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.7.3

#935 bump(sn-platform): bump sn-platform appVersion
  charts/sn-platform/Chart.yaml
Labels: doc-info-missing

#938 Upgrade confluent kafka version
  charts/sn-platform/values.yaml
Labels: no-need-doc

#940 update functionmesh repo location
  charts/sn-platform/README.md
Labels: doc-info-missing

#941 fix functionmesh repo
  charts/sn-platform/README.md
Labels: no-need-doc

#936 fix(toolset): fix proxy address in toolset configmap
  charts/sn-platform/templates/toolset/toolset-configmap.yaml
Labels: no-need-doc, release-sn-platform/1.8.1
