Repository streamnative/charts, pull requests merged in 2023-10, with the labels that each got.

#1109 Upgrade private cloud console version
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/values.yaml
Labels: doc-info-missing

#1111 Load the pulsar env as the program start options
  charts/pulsar/templates/bookkeeper/bookkeeper-cluster-initialize.yaml
Labels: doc-info-missing

#1116 Support Istio migration mode
  charts/sn-platform-slim/templates/broker/broker-cluster.yaml
  charts/sn-platform-slim/templates/istio/default-peerauthentication.yaml
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/istio/default-peerauthentication.yaml
  charts/sn-platform/values.yaml
Labels: doc-required

#1087 [charts/sn-platform] Add prometheus pod name to sts env
  charts/sn-platform/templates/prometheus/prometheus-configmap.yaml
  charts/sn-platform/templates/prometheus/prometheus-statefulset.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc

#1117 update operator name
  README.md
  charts/pulsar-operator/README.md
  charts/pulsar-operator/templates/NOTES.txt
Labels: no-need-doc

#1118 support external_labels on slim chart
  charts/sn-platform-slim/templates/prometheus/prometheus-configmap.yaml
  charts/sn-platform-slim/templates/prometheus/prometheus-statefulset.yaml
  charts/sn-platform-slim/values.yaml
Labels: no-need-doc

#1113 fix: detector missed the resources limit on server container
  charts/sn-platform-slim/templates/detector/pulsar-detector-deployment.yaml
  charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml
Labels: no-need-doc

#1115 feat: support extra configurions for the detector
  charts/sn-platform-slim/templates/detector/pulsar-detector-deployment.yaml
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc
