Repository streamnative/charts, pull requests merged in 2023-03, with the labels that each got.

#966 Replace k8s.gcr.io with registry.k8s.io
  charts/pulsar/templates/external-dns/external-dns.yaml
  charts/pulsar/values.yaml
  charts/sn-platform/templates/control-center/_control_center.tpl
  charts/sn-platform/values.yaml
Labels: doc-required

#937 Add snowflake connector
  charts/sn-platform/conf/broker/connectors.yaml
Labels: no-need-doc, do-not-merge

#963 [pulsar operators] bump pulsar operators kube supported version
  charts/pulsar-operator/Chart.yaml
Labels: no-need-doc

#969 [pulsar operators]: update the chart README & add the operator installing output
  charts/pulsar-operator/README.md
  charts/pulsar-operator/templates/NOTES.txt
Labels: no-need-doc

#968 bump snp image version to 2.10.3.4
  charts/sn-platform/values.yaml
Labels: no-need-doc

#967 feat: add Pulsar RestAPI config
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/values.yaml
Labels: doc-required

#971 Upgrade pulsar-operator to v0.15.2
  charts/pulsar-operator/Chart.yaml
  charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
  charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
  charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml
  charts/pulsar-operator/values.yaml
Labels: no-need-doc

#974 chore(sn-platform): bump snp chart version to 1.9
  charts/sn-platform/Chart.yaml
Labels: no-need-doc

#973 fix(sn-platform): fix several issues in sn-platform datadog templates
  charts/sn-platform/templates/bookkeeper/_bookkeeper.tpl
  charts/sn-platform/templates/broker/_broker.tpl
  charts/sn-platform/templates/prometheus/_prometheus.tpl
  charts/sn-platform/templates/proxy/_proxy.tpl
  charts/sn-platform/templates/zookeeper/_zookeeper.tpl
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.8.3

#976 replace logo
  charts/sn-console/Chart.yaml
  charts/sn-platform/Chart.yaml
  static/logo.svg
Labels: no-need-doc

#978 fix: change default memory in the examples
  examples/pulsar-operators/aop.yaml
  examples/pulsar-operators/kop.yaml
  examples/pulsar-operators/mop.yaml
  examples/pulsar-operators/proxy.yaml
  examples/pulsar-operators/quick-start.yaml
  examples/pulsar-operators/storage.yaml
Labels: no-need-doc

#977 [sn-platform]: update several images repo and version for CVE
  charts/sn-platform/values.yaml
Labels: no-need-doc

#979 [sn-platform] upgrade console image verison to v1.14.8
  charts/sn-platform/values.yaml
Labels: no-need-doc

#981 upgrade console image to v1.14.10
  charts/sn-platform/values.yaml
Labels: no-need-doc

#970 Support proxyroles for sn-platform
  charts/sn-platform/conf/vault/init_vault_streamnative_console/startup.sh
  charts/sn-platform/templates/_helpers.tpl
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/templates/proxy/proxy-cluster.yaml
  charts/sn-platform/values.yaml
Labels: doc-required

#983 fix internal issuer reference name.
  charts/sn-platform/templates/tls/istio/tls-certs.yaml
Labels: doc-info-missing

#985 [pulsar]: support upgrade to 2.10 image base to pulsar chart
  charts/pulsar/Chart.yaml
  charts/pulsar/templates/zookeeper/zookeeper-configmap.yaml
  charts/pulsar/templates/zookeeper/zookeeper-statefulset.yaml
  charts/pulsar/values.yaml
Labels: no-need-doc

#984 fix: kubeVersion limitation fix for operators chart
  charts/pulsar-operator/Chart.yaml
Labels: no-need-doc
