Repository streamnative/charts, pull requests merged in 2023-02, with the labels that each got.

#944 [pulsar-operator] Add Istio resource rbac for zk/bk operator
  charts/pulsar-operator/templates/bookkeeper-operator/rbac.yaml
  charts/pulsar-operator/templates/zookeeper-operator/rbac.yaml
Labels: no-need-doc

#942 [sn-platform] Fix broker secretRefs
  charts/sn-platform/templates/broker/broker-cluster.yaml
Labels: no-need-doc, release-sn-platform/1.8.2, release-sn-platform/1.7.4

#949 add jwt auth example
  examples/sn-platform/values-auth-jwt.yaml
  examples/sn-platform/values-external-zk.yaml
  examples/sn-platform/values-zk-dynamic-reconfig.yaml
Labels: no-need-doc

#951 upgrade pulsarctl default download version to support arm64(Apple M1)
  scripts/pulsar/common_auth.sh
Labels: no-need-doc

#947 fix(sn-platform): add back the datadog namespace config
  charts/sn-platform/templates/bookkeeper/_bookkeeper.tpl
  charts/sn-platform/templates/broker/_broker.tpl
  charts/sn-platform/templates/prometheus/_prometheus.tpl
  charts/sn-platform/templates/proxy/_proxy.tpl
  charts/sn-platform/templates/zookeeper/_zookeeper.tpl
  charts/sn-platform/values.yaml
Labels: doc-required

#955 [charts/sn-platform] Fix broken links
  charts/sn-platform/README.md
Labels: no-need-doc

#957 [sn-platform] Fix grafana dashboard
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.8.2

#958 upgrade console image to v1.14.7
  charts/sn-platform/values.yaml
Labels: no-need-doc, release-sn-platform/1.8.2

#948 Update the Repo README & several charts README
  README.md
  charts/function-mesh-operator/README.md
  charts/pulsar/README.md
  charts/sn-platform/README.md
Labels: doc

#939 [charts/sn-platform] - fix repeat ca tag
  charts/sn-platform/templates/tls/tls-cert-internal-issuer.yaml
Labels: no-need-doc, release-sn-platform/1.8.2

#960 Fix operators permission issue
  charts/pulsar-operator/templates/bookkeeper-operator/operator_rbac.yaml
  charts/pulsar-operator/templates/pulsar-operator/operator_rbac.yaml
  charts/pulsar-operator/templates/zookeeper-operator/operator_rbac.yaml
Labels: no-need-doc, release-pulsar-operators-release/0.14.2

#962 [pulsar operators]: add a operator quick-start example
  examples/pulsar-operators/quick-start.yaml
Labels: no-need-doc
