Repository streamnative/charts, pull requests merged in 2023-08, with the labels that each got.

#1085 Update README.md
  README.md
Labels: no-need-doc

#1082 Support custom token payload
  charts/sn-platform/conf/vault/init_vault_streamnative_console/startup.sh
  charts/sn-platform/templates/vault/vault-initialize.yaml
  charts/sn-platform/values.yaml
Labels: doc-info-missing

#1084 Add flag for support auto init jwt secret
  charts/sn-platform-slim/templates/toolset/jwt-secret-init-config.yaml
  charts/sn-platform-slim/templates/toolset/jwt-secret-init-job-service-account.yaml
  charts/sn-platform-slim/templates/toolset/jwt-secret-init-job.yaml
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/templates/toolset/jwt-secret-init-config.yaml
  charts/sn-platform/templates/toolset/jwt-secret-init-job-service-account.yaml
  charts/sn-platform/templates/toolset/jwt-secret-init-job.yaml
  charts/sn-platform/values.yaml
Labels: doc-required

#1090 fix: replace the toolset kafka container image
  charts/sn-platform/values.yaml
Labels: no-need-doc

#1088 fix: generate secret from json string
  charts/sn-platform-slim/templates/broker/broker-secret.yaml
  charts/sn-platform/templates/broker/broker-secret.yaml
Labels: no-need-doc, release/1.10.7

#1086 [sn-platform][sn-platform-slim]Upgrade private cloud console version
  charts/sn-platform-slim/templates/streamnative-console/streamnative-console-statefulset.yaml
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc, release/1.10.7

#1091 fix: update the offload config
  charts/sn-platform-slim/templates/broker/broker-cluster.yaml
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/values.yaml
Labels: doc-required

#1092 examples: add offload examples for pulsar operator
  examples/pulsar-operators/offload-aws-s3.yaml
  examples/pulsar-operators/offload-azureblob.yaml
  examples/pulsar-operators/offload-gcs.yaml
Labels: doc
