Repository streamnative/charts, pull requests merged in 2024-10, with the labels that each got.

#1183 feat: support autoscaling on broker and bookie
  charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml
  charts/sn-platform-slim/templates/broker/broker-cluster.yaml
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
  charts/sn-platform/templates/broker/broker-cluster.yaml
  charts/sn-platform/values.yaml
  examples/sn-platform/autoscaling-custom-metrics.yaml
  examples/sn-platform/autoscaling-resource-metrics.yaml
  examples/sn-platform/prometheus-adapter.yaml
Labels: doc

#1185 Fix console cves
  charts/sn-platform-slim/values.yaml
  charts/sn-platform/values.yaml
Labels: no-need-doc

#1187 Remove unused log conf
  charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml
  charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
Labels: doc-info-missing

#1186 upgrade console to v2.3.9
  charts/sn-platform-slim/values.yaml
Labels: no-need-doc
